import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import { mycokedb } from '../common/mycoke'

export default function Home(props) {

  return (
    <div className={''}>
      <Head>
        <title>Sports Hall Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/mcsstar.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
            <Login  data = {props.user}/>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://mcscocacola.mn/"
          target="_blank"
          rel="noopener noreferrer"
        >
         <p className='mx-3 font-semibold'> Sports Hall Booking </p>
          <span className={''}>
            <Image src="/images/logoCola.png" alt="Vercel Logo" width={300} height={23} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export const getServerSideProps = async (context) => {

  const user = await mycokedb.$queryRaw`select * from users`;

  return {
      props: {
          user: user
      }
  }
}
