import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import App from './components/App'

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Sports Hall Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/mcsstar.png" />
      </Head>

      <main className={''}>
        <App />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://mcscocacola.mn/"
          target="_blank"
          rel="noopener noreferrer"
        >
         <p className='mx-3 font-semibold'> Sports Hall Booking </p>
          <span className={''}>
            <Image src="/images/logoCola.png" alt="Vercel Logo" width={300} height={23} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
